### ISSUE TITLE
Flow failed as node_modules

### ISSUE THREAD

**Issue by mizchi** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#110] opened 2017-05-18 08:37 UTC
```
node_modules/babel-plugin-transform-react-remove-prop-types/src/index.js:83
 83:             const plugin = require(pluginName);
                                ^^^^^^^^^^^^^^^^^^^ The parameter passed to require() must be a literal string.


Found 1 error
```

**Comment by oliviertassinari** [comment] 2017-05-18 08:39
Duplicate of #107

**Closed by oliviertassinari** 2017-05-18 08:39 UTC
Labels: duplicate
