### ISSUE TITLE
Ability to remove `contextTypes`

### ISSUE THREAD

**Issue by eugef** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#173] opened 2018-11-22 14:15 UTC
Would be nice to remove `static contextTypes` from the components as well.

According to React documentation this static field is not required, only `static contextType` (singular form here!) is needed https://reactjs.org/docs/context.html#classcontexttype

**Comment by oliviertassinari** [comment] 2018-11-22 14:33
It's a duplicate of #77.

**Comment by oliviertassinari** [comment] 2018-11-22 14:33
As for the new context API, it can't be removed.

**Closed by oliviertassinari** 2018-11-22 14:33 UTC

**Comment by eugef** [comment] 2018-11-23 08:55
@oliviertassinari I double checked React 16 documentation about Context API and `contextTypes` are not mentioned there at all. I am also using Context API without defining any `contextTypes`  and it works as expected.

The only static field that is required for Context API is `contextType` https://reactjs.org/docs/context.html#classcontexttype

Please reconsider either re-opening this issue or PR #77

**Comment by oliviertassinari** [comment] 2018-11-23 09:01
@eugef I don't understand.

**Comment by eugef** [comment] 2018-11-23 13:16
With new Context API it is safe to remove `static contextTypes` because this filed is not required anymore

**Comment by oliviertassinari** [comment] 2018-11-23 13:17
`contextTypes` is a legacy API, you are not supposed to use it in the first place.
