### ISSUE TITLE
Remove propTypes object for indirect assignment

### ISSUE THREAD

**Issue by remcohaszing** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#75] opened 2017-01-20 14:14 UTC
This plugin removes the assignment of `propTypes` on react component, but it doesn't affect the referenced variable.

This means that the definition of the `propTypes` isn't removed.

For example:

```js
const propTypes = {
  value: PropTypes.string,
};


export default function MyComponent() {
  return <div />;
}


MyComponent.propTypes = propTypes;
```

Becomes:

```js
{
  value: PropTypes.string,
};


export default function MyComponent() {
  return <div />;
}
```

This is fine, except when referencing the `propTypes` from another component.

```js
import MyComponent from './MyComponent';


const propTypes = {
  value: MyComponent.propTypes.value,
};


export default MyOtherComponent(props) {
  return <MyComponent value={props.value} />;
}


MyOtherComponent.propTypes = propTypes;
```

After processing this becomes:

```js
import MyComponent from './MyComponent';


{
  value: MyComponent.propTypes.value,  // MyComponent.propTypes === undefined
};


export default MyOtherComponent(props) {
  return <MyComponent value={props.value} />;
}
```

This is a common use case, as this is the recommended way to define `propTypes` by the airbnb style guide (https://github.com/airbnb/javascript/tree/master/react#ordering)

I suggest to remove (or add an option to remove) the node that creates the `propTypes` object. So the latter example would simply become:

```js
import MyComponent from './MyComponent';


export default MyOtherComponent(props) {
  return <MyComponent value={props.value} />;
}
```

When using `wrap` mode, the indirect assignment should be turned into a direct assignment. So the first example would be transformed into:

```js
export default function MyComponent() {
  return <div />;
}


if (process.env.NODE_ENV !== 'production') {
  MyComponent.propTypes = {
    value: PropTypes.string,
  };
}
```

As a side effect, the bundle will become even smaller. :smile:

**Comment by oliviertassinari** [comment] 2017-01-20 15:21
> This is fine, except when referencing the propTypes from another component.

That's expected. I have added a section in the [documentation](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types#is-it-safe) for that. 
It's a duplicate of #70.

**Closed by oliviertassinari** 2017-01-20 15:21 UTC

**Comment by oliviertassinari** [comment] 2017-01-20 15:24
The path, I think we should follow, is discouraging users recycling the `propTypes`.

**Comment by oliviertassinari** [comment] 2017-01-20 22:08
> As a side effect, the bundle will become even smaller.

Actually, I'm wondering, why is this an issue at all. Isn't it a dead code that uglify should identify and remove?

**Comment by remcohaszing** [comment] 2017-01-22 18:06
I expected this as well, but apparently it doesn't.

<details>
<summary>*example.js*</summary>

```js
const PropTypes = {};
const MY_CONSTANT = 'MY_CONSTANT';
const MyComponent = {};
const propTypes = {
  foobar: PropTypes.string
};


if (process.env.NODE_ENV !== 'production') {
  MyComponent.propTypes = propTypes;
}

export default MyComponent;


```

</details>

<details>
<summary>*package.json*</summary>

```json
{
  "name": "webpack-bug",
  "scripts": {
    "build": "webpack -p"
  },
  "devDependencies": {
    "babel-core": "^6.22.1",
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.22.0",
    "webpack": "^2.2.0"
  },
  "babel": {
    "presets": [
      "es2015"
    ]
  }
}
```

</details>

<details>
<summary>*webpack.config.js*</summary>

```js
const path = require('path');


module.exports = {
  entry: path.join(__dirname, 'example.js'),
  output: {
    filename: 'out.js',
    path: 'out'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
      },
    ],
  },
  devtool: 'source-map',
};

```

</details>

<details>
<summary>*out/out.js*</summary>

```js
!function(e){function r(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}var t={};return r.m=e,r.c=t,r.i=function(e){return e},r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{configurable:!1,enumerable:!0,get:n})},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},r.p="",r(r.s=0)}([function(e,r,t){"use strict";Object.defineProperty(r,"__esModule",{value:!0});var n={},o={};({foobar:n.string});r.default=o}]);
//# sourceMappingURL=out.js.map

```

</details>

As seen in the output, an object is still created having a `foobar` property (near the end of *out.js*.

Additionally,

**Comment by lencioni** [comment] 2018-07-11 10:57
@oliviertassinari I'm seeing the same behavior. I think one cause of the unused variable not being removed is that if it contains any function calls the minifier won't remove it in case there are side-effects to the function calls.

I have noticed the additional problem that when using the `removeImport` option, the imports are also not removed since they are still referenced in the propTypes variable. So even if the minifier was removing the unused variable, it will not remove the imports.

I think this plugin should be enhanced so that it transforms code that looks like this:

```jsx
import React from 'react';
import PropTypes from 'prop-types';

const propTypes = {
  children: PropTypes.node,
};

export default class MyComponent extends React.Component {
  render() {
    return <div>{this.props.children}</div>;
  }
}

MyComponent.propTypes = propTypes;
```

into this:

```jsx
import React from 'react';

export default class MyComponent extends React.Component {
  render() {
    return <div>{this.props.children}</div>;
  }
}
```

At least for the simple case when it can be determined that the variable is no longer used.

Additionally, we often wrap our propTypes in a function when assigning it to the component, like this:

```jsx
import { forbidExtraProps } from 'airbnb-prop-types';

const propTypes = {
  // ...
};

class MyComponent extends React.Component {
  // ...
}

MyComponent.propTypes = forbidExtraProps(propTypes);
```

So the unused variable detection would ideally be smart enough to transform the above to:

```jsx
class MyComponent extends React.Component {
  // ...
}
```

What do you think? Is it worth taking a swing at this?

**Comment by lencioni** [comment] 2018-07-11 12:32
I opened up #145 to continue the discussion
